// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SRAMTemplate_30(	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7
  input        clock,
  input        io_r_req_valid,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  input  [8:0] io_r_req_bits_setIdx,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  output [1:0] io_r_resp_data_0,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  output [1:0] io_r_resp_data_1,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  output [1:0] io_r_resp_data_2,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  output [1:0] io_r_resp_data_3,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  output [1:0] io_r_resp_data_4,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  output [1:0] io_r_resp_data_5,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  output [1:0] io_r_resp_data_6,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  output [1:0] io_r_resp_data_7,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  input        io_w_req_valid,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  input  [8:0] io_w_req_bits_setIdx,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  input  [1:0] io_w_req_bits_data_0,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  input  [1:0] io_w_req_bits_data_1,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  input  [1:0] io_w_req_bits_data_2,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  input  [1:0] io_w_req_bits_data_3,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  input  [1:0] io_w_req_bits_data_4,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  input  [1:0] io_w_req_bits_data_5,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  input  [1:0] io_w_req_bits_data_6,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  input  [1:0] io_w_req_bits_data_7,	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
  input  [7:0] io_w_req_bits_waymask	// utility/src/main/scala/utility/SRAMTemplate.scala:98:14
);

  wire [15:0] _array_R0_data;	// utility/src/main/scala/utility/SRAMTemplate.scala:105:26
  reg  [1:0]  bypass_wdata_REG_0;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
  reg  [1:0]  bypass_wdata_REG_1;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
  reg  [1:0]  bypass_wdata_REG_2;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
  reg  [1:0]  bypass_wdata_REG_3;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
  reg  [1:0]  bypass_wdata_REG_4;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
  reg  [1:0]  bypass_wdata_REG_5;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
  reg  [1:0]  bypass_wdata_REG_6;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
  reg  [1:0]  bypass_wdata_REG_7;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
  reg         bypass_mask_need_check;	// utility/src/main/scala/utility/SRAMTemplate.scala:135:29
  reg  [8:0]  bypass_mask_waddr_reg;	// utility/src/main/scala/utility/SRAMTemplate.scala:136:28
  reg  [8:0]  bypass_mask_raddr_reg;	// utility/src/main/scala/utility/SRAMTemplate.scala:137:28
  reg  [7:0]  bypass_mask_bypass_REG;	// utility/src/main/scala/utility/SRAMTemplate.scala:139:76
  wire [7:0]  bypass_mask =
    {8{bypass_mask_need_check & bypass_mask_waddr_reg == bypass_mask_raddr_reg}}
    & bypass_mask_bypass_REG;	// utility/src/main/scala/utility/SRAMTemplate.scala:135:29, :136:28, :137:28, :139:{22,39,52,67,76}
  wire [1:0]  mem_rdata_0 = bypass_mask[0] ? bypass_wdata_REG_0 : _array_R0_data[1:0];	// utility/src/main/scala/utility/SRAMTemplate.scala:105:26, :139:67, :142:54, :147:30, :148:30
  wire [1:0]  mem_rdata_1 = bypass_mask[1] ? bypass_wdata_REG_1 : _array_R0_data[3:2];	// utility/src/main/scala/utility/SRAMTemplate.scala:105:26, :139:67, :142:54, :147:30, :148:30
  wire [1:0]  mem_rdata_2 = bypass_mask[2] ? bypass_wdata_REG_2 : _array_R0_data[5:4];	// utility/src/main/scala/utility/SRAMTemplate.scala:105:26, :139:67, :142:54, :147:30, :148:30
  wire [1:0]  mem_rdata_3 = bypass_mask[3] ? bypass_wdata_REG_3 : _array_R0_data[7:6];	// utility/src/main/scala/utility/SRAMTemplate.scala:105:26, :139:67, :142:54, :147:30, :148:30
  wire [1:0]  mem_rdata_4 = bypass_mask[4] ? bypass_wdata_REG_4 : _array_R0_data[9:8];	// utility/src/main/scala/utility/SRAMTemplate.scala:105:26, :139:67, :142:54, :147:30, :148:30
  wire [1:0]  mem_rdata_5 = bypass_mask[5] ? bypass_wdata_REG_5 : _array_R0_data[11:10];	// utility/src/main/scala/utility/SRAMTemplate.scala:105:26, :139:67, :142:54, :147:30, :148:30
  wire [1:0]  mem_rdata_6 = bypass_mask[6] ? bypass_wdata_REG_6 : _array_R0_data[13:12];	// utility/src/main/scala/utility/SRAMTemplate.scala:105:26, :139:67, :142:54, :147:30, :148:30
  wire [1:0]  mem_rdata_7 = bypass_mask[7] ? bypass_wdata_REG_7 : _array_R0_data[15:14];	// utility/src/main/scala/utility/SRAMTemplate.scala:105:26, :139:67, :142:54, :147:30, :148:30
  reg         rdata_REG;	// utility/src/main/scala/utility/SRAMTemplate.scala:153:59
  reg  [1:0]  rdata_hold_data_0;	// utility/src/main/scala/utility/Hold.scala:24:82
  reg  [1:0]  rdata_hold_data_1;	// utility/src/main/scala/utility/Hold.scala:24:82
  reg  [1:0]  rdata_hold_data_2;	// utility/src/main/scala/utility/Hold.scala:24:82
  reg  [1:0]  rdata_hold_data_3;	// utility/src/main/scala/utility/Hold.scala:24:82
  reg  [1:0]  rdata_hold_data_4;	// utility/src/main/scala/utility/Hold.scala:24:82
  reg  [1:0]  rdata_hold_data_5;	// utility/src/main/scala/utility/Hold.scala:24:82
  reg  [1:0]  rdata_hold_data_6;	// utility/src/main/scala/utility/Hold.scala:24:82
  reg  [1:0]  rdata_hold_data_7;	// utility/src/main/scala/utility/Hold.scala:24:82
  always @(posedge clock) begin
    bypass_wdata_REG_0 <= io_w_req_bits_data_0;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
    bypass_wdata_REG_1 <= io_w_req_bits_data_1;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
    bypass_wdata_REG_2 <= io_w_req_bits_data_2;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
    bypass_wdata_REG_3 <= io_w_req_bits_data_3;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
    bypass_wdata_REG_4 <= io_w_req_bits_data_4;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
    bypass_wdata_REG_5 <= io_w_req_bits_data_5;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
    bypass_wdata_REG_6 <= io_w_req_bits_data_6;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
    bypass_wdata_REG_7 <= io_w_req_bits_data_7;	// utility/src/main/scala/utility/SRAMTemplate.scala:142:54
    bypass_mask_need_check <= io_r_req_valid & io_w_req_valid;	// utility/src/main/scala/utility/SRAMTemplate.scala:135:{29,34}
    bypass_mask_waddr_reg <= io_w_req_bits_setIdx;	// utility/src/main/scala/utility/SRAMTemplate.scala:136:28
    bypass_mask_raddr_reg <= io_r_req_bits_setIdx;	// utility/src/main/scala/utility/SRAMTemplate.scala:137:28
    bypass_mask_bypass_REG <= io_w_req_bits_waymask;	// utility/src/main/scala/utility/SRAMTemplate.scala:139:76
    rdata_REG <= io_r_req_valid;	// utility/src/main/scala/utility/SRAMTemplate.scala:153:59
    if (rdata_REG) begin	// utility/src/main/scala/utility/SRAMTemplate.scala:153:59
      rdata_hold_data_0 <= mem_rdata_0;	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:148:30
      rdata_hold_data_1 <= mem_rdata_1;	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:148:30
      rdata_hold_data_2 <= mem_rdata_2;	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:148:30
      rdata_hold_data_3 <= mem_rdata_3;	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:148:30
      rdata_hold_data_4 <= mem_rdata_4;	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:148:30
      rdata_hold_data_5 <= mem_rdata_5;	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:148:30
      rdata_hold_data_6 <= mem_rdata_6;	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:148:30
      rdata_hold_data_7 <= mem_rdata_7;	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:148:30
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7
    `ifdef FIRRTL_BEFORE_INITIAL	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7
      `FIRRTL_BEFORE_INITIAL	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7
    initial begin	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7
      `ifdef INIT_RANDOM_PROLOG_	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7
        `INIT_RANDOM_PROLOG_	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7
        end	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7
        bypass_wdata_REG_0 = _RANDOM[1'h0][1:0];	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :142:54
        bypass_wdata_REG_1 = _RANDOM[1'h0][3:2];	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :142:54
        bypass_wdata_REG_2 = _RANDOM[1'h0][5:4];	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :142:54
        bypass_wdata_REG_3 = _RANDOM[1'h0][7:6];	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :142:54
        bypass_wdata_REG_4 = _RANDOM[1'h0][9:8];	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :142:54
        bypass_wdata_REG_5 = _RANDOM[1'h0][11:10];	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :142:54
        bypass_wdata_REG_6 = _RANDOM[1'h0][13:12];	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :142:54
        bypass_wdata_REG_7 = _RANDOM[1'h0][15:14];	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :142:54
        bypass_mask_need_check = _RANDOM[1'h0][16];	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :135:29, :142:54
        bypass_mask_waddr_reg = _RANDOM[1'h0][25:17];	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :136:28, :142:54
        bypass_mask_raddr_reg = {_RANDOM[1'h0][31:26], _RANDOM[1'h1][2:0]};	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :137:28, :142:54
        bypass_mask_bypass_REG = _RANDOM[1'h1][10:3];	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :137:28, :139:76
        rdata_REG = _RANDOM[1'h1][11];	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :137:28, :153:59
        rdata_hold_data_0 = _RANDOM[1'h1][13:12];	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :137:28
        rdata_hold_data_1 = _RANDOM[1'h1][15:14];	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :137:28
        rdata_hold_data_2 = _RANDOM[1'h1][17:16];	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :137:28
        rdata_hold_data_3 = _RANDOM[1'h1][19:18];	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :137:28
        rdata_hold_data_4 = _RANDOM[1'h1][21:20];	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :137:28
        rdata_hold_data_5 = _RANDOM[1'h1][23:22];	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :137:28
        rdata_hold_data_6 = _RANDOM[1'h1][25:24];	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :137:28
        rdata_hold_data_7 = _RANDOM[1'h1][27:26];	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :137:28
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7
      `FIRRTL_AFTER_INITIAL	// utility/src/main/scala/utility/SRAMTemplate.scala:93:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  array_6 array (	// utility/src/main/scala/utility/SRAMTemplate.scala:105:26
    .R0_addr (io_r_req_bits_setIdx),
    .R0_en   (io_r_req_valid),
    .R0_clk  (clock),
    .R0_data (_array_R0_data),
    .W0_addr (io_w_req_bits_setIdx),
    .W0_en   (io_w_req_valid),
    .W0_clk  (clock),
    .W0_data
      ({io_w_req_bits_data_7,
        io_w_req_bits_data_6,
        io_w_req_bits_data_5,
        io_w_req_bits_data_4,
        io_w_req_bits_data_3,
        io_w_req_bits_data_2,
        io_w_req_bits_data_1,
        io_w_req_bits_data_0}),	// utility/src/main/scala/utility/SRAMTemplate.scala:105:26
    .W0_mask (io_w_req_bits_waymask)
  );
  assign io_r_resp_data_0 = rdata_REG ? mem_rdata_0 : rdata_hold_data_0;	// utility/src/main/scala/utility/Hold.scala:24:82, :25:8, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :148:30, :153:59
  assign io_r_resp_data_1 = rdata_REG ? mem_rdata_1 : rdata_hold_data_1;	// utility/src/main/scala/utility/Hold.scala:24:82, :25:8, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :148:30, :153:59
  assign io_r_resp_data_2 = rdata_REG ? mem_rdata_2 : rdata_hold_data_2;	// utility/src/main/scala/utility/Hold.scala:24:82, :25:8, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :148:30, :153:59
  assign io_r_resp_data_3 = rdata_REG ? mem_rdata_3 : rdata_hold_data_3;	// utility/src/main/scala/utility/Hold.scala:24:82, :25:8, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :148:30, :153:59
  assign io_r_resp_data_4 = rdata_REG ? mem_rdata_4 : rdata_hold_data_4;	// utility/src/main/scala/utility/Hold.scala:24:82, :25:8, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :148:30, :153:59
  assign io_r_resp_data_5 = rdata_REG ? mem_rdata_5 : rdata_hold_data_5;	// utility/src/main/scala/utility/Hold.scala:24:82, :25:8, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :148:30, :153:59
  assign io_r_resp_data_6 = rdata_REG ? mem_rdata_6 : rdata_hold_data_6;	// utility/src/main/scala/utility/Hold.scala:24:82, :25:8, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :148:30, :153:59
  assign io_r_resp_data_7 = rdata_REG ? mem_rdata_7 : rdata_hold_data_7;	// utility/src/main/scala/utility/Hold.scala:24:82, :25:8, utility/src/main/scala/utility/SRAMTemplate.scala:93:7, :148:30, :153:59
endmodule

