// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SRAMTemplate_35(	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
  input        clock,	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
  input        reset,	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
  input        io_r_req_valid,	// @[utility/src/main/scala/utility/SRAMTemplate.scala:144:14]
  input  [7:0] io_r_req_bits_setIdx,	// @[utility/src/main/scala/utility/SRAMTemplate.scala:144:14]
  output [5:0] io_r_resp_data_0,	// @[utility/src/main/scala/utility/SRAMTemplate.scala:144:14]
  output [5:0] io_r_resp_data_1,	// @[utility/src/main/scala/utility/SRAMTemplate.scala:144:14]
  output [5:0] io_r_resp_data_2,	// @[utility/src/main/scala/utility/SRAMTemplate.scala:144:14]
  output [5:0] io_r_resp_data_3,	// @[utility/src/main/scala/utility/SRAMTemplate.scala:144:14]
  input        io_w_req_valid,	// @[utility/src/main/scala/utility/SRAMTemplate.scala:144:14]
  input  [7:0] io_w_req_bits_setIdx,	// @[utility/src/main/scala/utility/SRAMTemplate.scala:144:14]
  input  [5:0] io_w_req_bits_data_0,	// @[utility/src/main/scala/utility/SRAMTemplate.scala:144:14]
  input  [5:0] io_w_req_bits_data_1,	// @[utility/src/main/scala/utility/SRAMTemplate.scala:144:14]
  input  [5:0] io_w_req_bits_data_2,	// @[utility/src/main/scala/utility/SRAMTemplate.scala:144:14]
  input  [5:0] io_w_req_bits_data_3,	// @[utility/src/main/scala/utility/SRAMTemplate.scala:144:14]
  input  [3:0] io_w_req_bits_waymask	// @[utility/src/main/scala/utility/SRAMTemplate.scala:144:14]
);

  wire [23:0] _array_R0_data;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:154:26]
  reg         _resetState;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:158:30]
  reg  [7:0]  _resetSet;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg  [5:0]  bypass_wdata_r_0;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:207:56]
  reg  [5:0]  bypass_wdata_r_1;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:207:56]
  reg  [5:0]  bypass_wdata_r_2;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:207:56]
  reg  [5:0]  bypass_wdata_r_3;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:207:56]
  wire        bypass_mask_need_check = io_r_req_valid & io_w_req_valid;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:198:26]
  reg         bypass_mask_need_check_reg_last_r;	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22]
  reg  [7:0]  bypass_mask_waddr_reg;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:200:30]
  reg  [7:0]  bypass_mask_raddr_reg;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:201:30]
  reg  [3:0]  bypass_mask_wmask_reg;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:202:30]
  wire [3:0]  bypass_mask =
    {4{bypass_mask_need_check_reg_last_r
         & bypass_mask_waddr_reg == bypass_mask_raddr_reg}} & bypass_mask_wmask_reg;	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22, utility/src/main/scala/utility/SRAMTemplate.scala:200:30, :201:30, :202:30, :204:{22,43,56,71}]
  wire [5:0]  mem_rdata_0 = bypass_mask[0] ? bypass_wdata_r_0 : _array_R0_data[5:0];	// @[utility/src/main/scala/utility/SRAMTemplate.scala:154:26, :192:69, :204:71, :207:56, :212:30, :213:30]
  wire [5:0]  mem_rdata_1 = bypass_mask[1] ? bypass_wdata_r_1 : _array_R0_data[11:6];	// @[utility/src/main/scala/utility/SRAMTemplate.scala:154:26, :192:69, :204:71, :207:56, :212:30, :213:30]
  wire [5:0]  mem_rdata_2 = bypass_mask[2] ? bypass_wdata_r_2 : _array_R0_data[17:12];	// @[utility/src/main/scala/utility/SRAMTemplate.scala:154:26, :192:69, :204:71, :207:56, :212:30, :213:30]
  wire [5:0]  mem_rdata_3 = bypass_mask[3] ? bypass_wdata_r_3 : _array_R0_data[23:18];	// @[utility/src/main/scala/utility/SRAMTemplate.scala:154:26, :192:69, :204:71, :207:56, :212:30, :213:30]
  reg         rdata_last_r;	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22]
  reg  [5:0]  rdata_hold_data_0;	// @[utility/src/main/scala/utility/Hold.scala:24:82]
  reg  [5:0]  rdata_hold_data_1;	// @[utility/src/main/scala/utility/Hold.scala:24:82]
  reg  [5:0]  rdata_hold_data_2;	// @[utility/src/main/scala/utility/Hold.scala:24:82]
  reg  [5:0]  rdata_hold_data_3;	// @[utility/src/main/scala/utility/Hold.scala:24:82]
  always @(posedge clock or posedge reset) begin	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
    if (reset) begin	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
      _resetState <= 1'h1;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :158:30]
      _resetSet <= 8'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
      bypass_mask_need_check_reg_last_r <= 1'h0;	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22, utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
      rdata_last_r <= 1'h0;	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22, utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
    end
    else begin	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
      _resetState <= ~(_resetState & (&_resetSet)) & _resetState;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :73:24, :117:24, :118:{16,23}, utility/src/main/scala/utility/SRAMTemplate.scala:158:30, :160:{24,38}]
      if (_resetState)	// @[utility/src/main/scala/utility/SRAMTemplate.scala:158:30]
        _resetSet <= 8'(_resetSet + 8'h1);	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      if (bypass_mask_need_check | bypass_mask_need_check_reg_last_r)	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:{22,40}, utility/src/main/scala/utility/SRAMTemplate.scala:198:26]
        bypass_mask_need_check_reg_last_r <= bypass_mask_need_check;	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22, utility/src/main/scala/utility/SRAMTemplate.scala:198:26]
      if (io_r_req_valid | rdata_last_r)	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:{22,40}]
        rdata_last_r <= io_r_req_valid;	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22]
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
    if (io_w_req_valid & io_r_req_valid) begin	// @[utility/src/main/scala/utility/SRAMTemplate.scala:207:92]
      bypass_wdata_r_0 <= io_w_req_bits_data_0;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:207:56]
      bypass_wdata_r_1 <= io_w_req_bits_data_1;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:207:56]
      bypass_wdata_r_2 <= io_w_req_bits_data_2;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:207:56]
      bypass_wdata_r_3 <= io_w_req_bits_data_3;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:207:56]
    end
    if (bypass_mask_need_check) begin	// @[utility/src/main/scala/utility/SRAMTemplate.scala:198:26]
      bypass_mask_waddr_reg <= io_w_req_bits_setIdx;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:200:30]
      bypass_mask_raddr_reg <= io_r_req_bits_setIdx;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:201:30]
      bypass_mask_wmask_reg <= io_w_req_bits_waymask;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:202:30]
    end
    if (rdata_last_r) begin	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22]
      rdata_hold_data_0 <= mem_rdata_0;	// @[utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:213:30]
      rdata_hold_data_1 <= mem_rdata_1;	// @[utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:213:30]
      rdata_hold_data_2 <= mem_rdata_2;	// @[utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:213:30]
      rdata_hold_data_3 <= mem_rdata_3;	// @[utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:213:30]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
      `FIRRTL_BEFORE_INITIAL	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
    initial begin	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
        `INIT_RANDOM_PROLOG_	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
        end	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
        _resetState = _RANDOM[2'h0][0];	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :158:30]
        _resetSet = _RANDOM[2'h0][8:1];	// @[src/main/scala/chisel3/util/Counter.scala:61:40, utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :158:30]
        bypass_wdata_r_0 = _RANDOM[2'h0][14:9];	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :158:30, :207:56]
        bypass_wdata_r_1 = _RANDOM[2'h0][20:15];	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :158:30, :207:56]
        bypass_wdata_r_2 = _RANDOM[2'h0][26:21];	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :158:30, :207:56]
        bypass_wdata_r_3 = {_RANDOM[2'h0][31:27], _RANDOM[2'h1][0]};	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :158:30, :207:56]
        bypass_mask_need_check_reg_last_r = _RANDOM[2'h1][1];	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22, utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :207:56]
        bypass_mask_waddr_reg = _RANDOM[2'h1][9:2];	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :200:30, :207:56]
        bypass_mask_raddr_reg = _RANDOM[2'h1][17:10];	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :201:30, :207:56]
        bypass_mask_wmask_reg = _RANDOM[2'h1][21:18];	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :202:30, :207:56]
        rdata_last_r = _RANDOM[2'h1][22];	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22, utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :207:56]
        rdata_hold_data_0 = _RANDOM[2'h1][28:23];	// @[utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :207:56]
        rdata_hold_data_1 = {_RANDOM[2'h1][31:29], _RANDOM[2'h2][2:0]};	// @[utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :207:56]
        rdata_hold_data_2 = _RANDOM[2'h2][8:3];	// @[utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
        rdata_hold_data_3 = _RANDOM[2'h2][14:9];	// @[utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
        _resetState = 1'h1;	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :158:30]
        _resetSet = 8'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
        bypass_mask_need_check_reg_last_r = 1'h0;	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22, utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
        rdata_last_r = 1'h0;	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22, utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
      `FIRRTL_AFTER_INITIAL	// @[utility/src/main/scala/utility/SRAMTemplate.scala:138:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  array_7 array (	// @[utility/src/main/scala/utility/SRAMTemplate.scala:154:26]
    .R0_addr (io_r_req_bits_setIdx),
    .R0_en   (io_r_req_valid),
    .R0_clk  (clock),
    .R0_data (_array_R0_data),
    .W0_addr (_resetState ? _resetSet : io_w_req_bits_setIdx),	// @[src/main/scala/chisel3/util/Counter.scala:61:40, utility/src/main/scala/utility/SRAMTemplate.scala:158:30, :174:19]
    .W0_en   (io_w_req_valid | _resetState),	// @[utility/src/main/scala/utility/SRAMTemplate.scala:158:30, :171:52]
    .W0_clk  (clock),
    .W0_data
      ({_resetState ? 6'h0 : io_w_req_bits_data_3,
        _resetState ? 6'h0 : io_w_req_bits_data_2,
        _resetState ? 6'h0 : io_w_req_bits_data_1,
        _resetState ? 6'h0 : io_w_req_bits_data_0}),	// @[utility/src/main/scala/utility/SRAMTemplate.scala:158:30, :175:{18,43}, :176:13]
    .W0_mask (_resetState ? 4'hF : io_w_req_bits_waymask)	// @[utility/src/main/scala/utility/SRAMTemplate.scala:158:30, :180:{22,39}]
  );
  assign io_r_resp_data_0 = rdata_last_r ? mem_rdata_0 : rdata_hold_data_0;	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22, utility/src/main/scala/utility/Hold.scala:24:82, :25:8, utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :213:30]
  assign io_r_resp_data_1 = rdata_last_r ? mem_rdata_1 : rdata_hold_data_1;	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22, utility/src/main/scala/utility/Hold.scala:24:82, :25:8, utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :213:30]
  assign io_r_resp_data_2 = rdata_last_r ? mem_rdata_2 : rdata_hold_data_2;	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22, utility/src/main/scala/utility/Hold.scala:24:82, :25:8, utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :213:30]
  assign io_r_resp_data_3 = rdata_last_r ? mem_rdata_3 : rdata_hold_data_3;	// @[utility/src/main/scala/utility/ClockGatedReg.scala:25:22, utility/src/main/scala/utility/Hold.scala:24:82, :25:8, utility/src/main/scala/utility/SRAMTemplate.scala:138:7, :213:30]
endmodule

