// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module DelayNWithValid_1(	// @[utility/src/main/scala/utility/Hold.scala:106:7]
  input         clock,	// @[utility/src/main/scala/utility/Hold.scala:106:7]
  input         reset,	// @[utility/src/main/scala/utility/Hold.scala:106:7]
  input         io_in_bits_valid,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input  [3:0]  io_in_bits_brSlots_0_offset,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input  [11:0] io_in_bits_brSlots_0_lower,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input  [1:0]  io_in_bits_brSlots_0_tarStat,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input         io_in_bits_brSlots_0_sharing,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input         io_in_bits_brSlots_0_valid,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input  [3:0]  io_in_bits_tailSlot_offset,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input  [19:0] io_in_bits_tailSlot_lower,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input  [1:0]  io_in_bits_tailSlot_tarStat,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input         io_in_bits_tailSlot_sharing,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input         io_in_bits_tailSlot_valid,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input  [3:0]  io_in_bits_pftAddr,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input         io_in_bits_carry,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input         io_in_bits_isCall,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input         io_in_bits_isRet,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input         io_in_bits_isJalr,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input         io_in_bits_last_may_be_rvi_call,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input         io_in_bits_always_taken_0,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input         io_in_bits_always_taken_1,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  input         io_in_valid,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output        io_out_bits_valid,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output [3:0]  io_out_bits_brSlots_0_offset,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output [11:0] io_out_bits_brSlots_0_lower,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output [1:0]  io_out_bits_brSlots_0_tarStat,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output        io_out_bits_brSlots_0_sharing,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output        io_out_bits_brSlots_0_valid,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output [3:0]  io_out_bits_tailSlot_offset,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output [19:0] io_out_bits_tailSlot_lower,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output [1:0]  io_out_bits_tailSlot_tarStat,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output        io_out_bits_tailSlot_sharing,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output        io_out_bits_tailSlot_valid,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output [3:0]  io_out_bits_pftAddr,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output        io_out_bits_carry,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output        io_out_bits_isCall,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output        io_out_bits_isRet,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output        io_out_bits_isJalr,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output        io_out_bits_last_may_be_rvi_call,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output        io_out_bits_always_taken_0,	// @[utility/src/main/scala/utility/Hold.scala:107:14]
  output        io_out_bits_always_taken_1	// @[utility/src/main/scala/utility/Hold.scala:107:14]
);

  reg        valid_REG;	// @[utility/src/main/scala/utility/Hold.scala:117:25]
  reg        data_valid;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg [3:0]  data_brSlots_0_offset;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg [11:0] data_brSlots_0_lower;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg [1:0]  data_brSlots_0_tarStat;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        data_brSlots_0_sharing;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        data_brSlots_0_valid;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg [3:0]  data_tailSlot_offset;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg [19:0] data_tailSlot_lower;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg [1:0]  data_tailSlot_tarStat;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        data_tailSlot_sharing;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        data_tailSlot_valid;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg [3:0]  data_pftAddr;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        data_carry;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        data_isCall;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        data_isRet;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        data_isJalr;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        data_last_may_be_rvi_call;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        data_always_taken_0;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        data_always_taken_1;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        res_bits_valid;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg [3:0]  res_bits_brSlots_0_offset;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg [11:0] res_bits_brSlots_0_lower;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg [1:0]  res_bits_brSlots_0_tarStat;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        res_bits_brSlots_0_sharing;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        res_bits_brSlots_0_valid;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg [3:0]  res_bits_tailSlot_offset;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg [19:0] res_bits_tailSlot_lower;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg [1:0]  res_bits_tailSlot_tarStat;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        res_bits_tailSlot_sharing;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        res_bits_tailSlot_valid;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg [3:0]  res_bits_pftAddr;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        res_bits_carry;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        res_bits_isCall;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        res_bits_isRet;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        res_bits_isJalr;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        res_bits_last_may_be_rvi_call;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        res_bits_always_taken_0;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  reg        res_bits_always_taken_1;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
  always @(posedge clock or posedge reset) begin	// @[utility/src/main/scala/utility/Hold.scala:106:7]
    if (reset)	// @[utility/src/main/scala/utility/Hold.scala:106:7]
      valid_REG <= 1'h0;	// @[utility/src/main/scala/utility/Hold.scala:117:25]
    else	// @[utility/src/main/scala/utility/Hold.scala:106:7]
      valid_REG <= io_in_valid;	// @[utility/src/main/scala/utility/Hold.scala:117:25]
  end // always @(posedge, posedge)
  always @(posedge clock) begin	// @[utility/src/main/scala/utility/Hold.scala:106:7]
    if (io_in_valid) begin	// @[utility/src/main/scala/utility/Hold.scala:107:14]
      data_valid <= io_in_bits_valid;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_brSlots_0_offset <= io_in_bits_brSlots_0_offset;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_brSlots_0_lower <= io_in_bits_brSlots_0_lower;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_brSlots_0_tarStat <= io_in_bits_brSlots_0_tarStat;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_brSlots_0_sharing <= io_in_bits_brSlots_0_sharing;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_brSlots_0_valid <= io_in_bits_brSlots_0_valid;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_tailSlot_offset <= io_in_bits_tailSlot_offset;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_tailSlot_lower <= io_in_bits_tailSlot_lower;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_tailSlot_tarStat <= io_in_bits_tailSlot_tarStat;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_tailSlot_sharing <= io_in_bits_tailSlot_sharing;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_tailSlot_valid <= io_in_bits_tailSlot_valid;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_pftAddr <= io_in_bits_pftAddr;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_carry <= io_in_bits_carry;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_isCall <= io_in_bits_isCall;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_isRet <= io_in_bits_isRet;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_isJalr <= io_in_bits_isJalr;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_last_may_be_rvi_call <= io_in_bits_last_may_be_rvi_call;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_always_taken_0 <= io_in_bits_always_taken_0;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      data_always_taken_1 <= io_in_bits_always_taken_1;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
    end
    if (valid_REG) begin	// @[utility/src/main/scala/utility/Hold.scala:117:25]
      res_bits_valid <= data_valid;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_brSlots_0_offset <= data_brSlots_0_offset;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_brSlots_0_lower <= data_brSlots_0_lower;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_brSlots_0_tarStat <= data_brSlots_0_tarStat;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_brSlots_0_sharing <= data_brSlots_0_sharing;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_brSlots_0_valid <= data_brSlots_0_valid;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_tailSlot_offset <= data_tailSlot_offset;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_tailSlot_lower <= data_tailSlot_lower;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_tailSlot_tarStat <= data_tailSlot_tarStat;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_tailSlot_sharing <= data_tailSlot_sharing;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_tailSlot_valid <= data_tailSlot_valid;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_pftAddr <= data_pftAddr;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_carry <= data_carry;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_isCall <= data_isCall;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_isRet <= data_isRet;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_isJalr <= data_isJalr;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_last_may_be_rvi_call <= data_last_may_be_rvi_call;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_always_taken_0 <= data_always_taken_0;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
      res_bits_always_taken_1 <= data_always_taken_1;	// @[utility/src/main/scala/utility/Hold.scala:121:27]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[utility/src/main/scala/utility/Hold.scala:106:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[utility/src/main/scala/utility/Hold.scala:106:7]
      `FIRRTL_BEFORE_INITIAL	// @[utility/src/main/scala/utility/Hold.scala:106:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];	// @[utility/src/main/scala/utility/Hold.scala:106:7]
    initial begin	// @[utility/src/main/scala/utility/Hold.scala:106:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[utility/src/main/scala/utility/Hold.scala:106:7]
        `INIT_RANDOM_PROLOG_	// @[utility/src/main/scala/utility/Hold.scala:106:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[utility/src/main/scala/utility/Hold.scala:106:7]
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// @[utility/src/main/scala/utility/Hold.scala:106:7]
        end	// @[utility/src/main/scala/utility/Hold.scala:106:7]
        valid_REG = _RANDOM[2'h0][0];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :117:25]
        data_valid = _RANDOM[2'h0][1];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :117:25, :121:27]
        data_brSlots_0_offset = _RANDOM[2'h0][5:2];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :117:25, :121:27]
        data_brSlots_0_lower = _RANDOM[2'h0][17:6];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :117:25, :121:27]
        data_brSlots_0_tarStat = _RANDOM[2'h0][19:18];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :117:25, :121:27]
        data_brSlots_0_sharing = _RANDOM[2'h0][20];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :117:25, :121:27]
        data_brSlots_0_valid = _RANDOM[2'h0][21];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :117:25, :121:27]
        data_tailSlot_offset = _RANDOM[2'h0][25:22];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :117:25, :121:27]
        data_tailSlot_lower = {_RANDOM[2'h0][31:26], _RANDOM[2'h1][13:0]};	// @[utility/src/main/scala/utility/Hold.scala:106:7, :117:25, :121:27]
        data_tailSlot_tarStat = _RANDOM[2'h1][15:14];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        data_tailSlot_sharing = _RANDOM[2'h1][16];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        data_tailSlot_valid = _RANDOM[2'h1][17];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        data_pftAddr = _RANDOM[2'h1][21:18];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        data_carry = _RANDOM[2'h1][22];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        data_isCall = _RANDOM[2'h1][23];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        data_isRet = _RANDOM[2'h1][24];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        data_isJalr = _RANDOM[2'h1][25];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        data_last_may_be_rvi_call = _RANDOM[2'h1][26];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        data_always_taken_0 = _RANDOM[2'h1][27];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        data_always_taken_1 = _RANDOM[2'h1][28];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_valid = _RANDOM[2'h1][30];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_brSlots_0_offset = {_RANDOM[2'h1][31], _RANDOM[2'h2][2:0]};	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_brSlots_0_lower = _RANDOM[2'h2][14:3];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_brSlots_0_tarStat = _RANDOM[2'h2][16:15];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_brSlots_0_sharing = _RANDOM[2'h2][17];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_brSlots_0_valid = _RANDOM[2'h2][18];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_tailSlot_offset = _RANDOM[2'h2][22:19];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_tailSlot_lower = {_RANDOM[2'h2][31:23], _RANDOM[2'h3][10:0]};	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_tailSlot_tarStat = _RANDOM[2'h3][12:11];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_tailSlot_sharing = _RANDOM[2'h3][13];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_tailSlot_valid = _RANDOM[2'h3][14];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_pftAddr = _RANDOM[2'h3][18:15];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_carry = _RANDOM[2'h3][19];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_isCall = _RANDOM[2'h3][20];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_isRet = _RANDOM[2'h3][21];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_isJalr = _RANDOM[2'h3][22];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_last_may_be_rvi_call = _RANDOM[2'h3][23];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_always_taken_0 = _RANDOM[2'h3][24];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
        res_bits_always_taken_1 = _RANDOM[2'h3][25];	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
      `endif // RANDOMIZE_REG_INIT
      if (reset)	// @[utility/src/main/scala/utility/Hold.scala:106:7]
        valid_REG = 1'h0;	// @[utility/src/main/scala/utility/Hold.scala:117:25]
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[utility/src/main/scala/utility/Hold.scala:106:7]
      `FIRRTL_AFTER_INITIAL	// @[utility/src/main/scala/utility/Hold.scala:106:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_bits_valid = res_bits_valid;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_brSlots_0_offset = res_bits_brSlots_0_offset;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_brSlots_0_lower = res_bits_brSlots_0_lower;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_brSlots_0_tarStat = res_bits_brSlots_0_tarStat;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_brSlots_0_sharing = res_bits_brSlots_0_sharing;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_brSlots_0_valid = res_bits_brSlots_0_valid;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_tailSlot_offset = res_bits_tailSlot_offset;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_tailSlot_lower = res_bits_tailSlot_lower;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_tailSlot_tarStat = res_bits_tailSlot_tarStat;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_tailSlot_sharing = res_bits_tailSlot_sharing;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_tailSlot_valid = res_bits_tailSlot_valid;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_pftAddr = res_bits_pftAddr;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_carry = res_bits_carry;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_isCall = res_bits_isCall;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_isRet = res_bits_isRet;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_isJalr = res_bits_isJalr;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_last_may_be_rvi_call = res_bits_last_may_be_rvi_call;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_always_taken_0 = res_bits_always_taken_0;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
  assign io_out_bits_always_taken_1 = res_bits_always_taken_1;	// @[utility/src/main/scala/utility/Hold.scala:106:7, :121:27]
endmodule

