// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module FoldedSRAMTemplate_25(	// utility/src/main/scala/utility/SRAMTemplate.scala:162:7
  input         clock,
  input         reset,
  input         io_r_req_valid,	// utility/src/main/scala/utility/SRAMTemplate.scala:165:14
  input  [7:0]  io_r_req_bits_setIdx,	// utility/src/main/scala/utility/SRAMTemplate.scala:165:14
  output [8:0]  io_r_resp_data_0_tag,	// utility/src/main/scala/utility/SRAMTemplate.scala:165:14
  output [1:0]  io_r_resp_data_0_ctr,	// utility/src/main/scala/utility/SRAMTemplate.scala:165:14
  output [38:0] io_r_resp_data_0_target,	// utility/src/main/scala/utility/SRAMTemplate.scala:165:14
  input         io_w_req_valid,	// utility/src/main/scala/utility/SRAMTemplate.scala:165:14
  input  [7:0]  io_w_req_bits_setIdx,	// utility/src/main/scala/utility/SRAMTemplate.scala:165:14
  input  [8:0]  io_w_req_bits_data_0_tag,	// utility/src/main/scala/utility/SRAMTemplate.scala:165:14
  input  [1:0]  io_w_req_bits_data_0_ctr,	// utility/src/main/scala/utility/SRAMTemplate.scala:165:14
  input  [38:0] io_w_req_bits_data_0_target	// utility/src/main/scala/utility/SRAMTemplate.scala:165:14
);

  wire [8:0]  _array_io_r_resp_data_0_tag;	// utility/src/main/scala/utility/SRAMTemplate.scala:179:21
  wire [1:0]  _array_io_r_resp_data_0_ctr;	// utility/src/main/scala/utility/SRAMTemplate.scala:179:21
  wire [38:0] _array_io_r_resp_data_0_target;	// utility/src/main/scala/utility/SRAMTemplate.scala:179:21
  wire [8:0]  _array_io_r_resp_data_1_tag;	// utility/src/main/scala/utility/SRAMTemplate.scala:179:21
  wire [1:0]  _array_io_r_resp_data_1_ctr;	// utility/src/main/scala/utility/SRAMTemplate.scala:179:21
  wire [38:0] _array_io_r_resp_data_1_target;	// utility/src/main/scala/utility/SRAMTemplate.scala:179:21
  reg         ridx;	// utility/src/main/scala/utility/SRAMTemplate.scala:189:21
  reg         holdRidx_REG;	// utility/src/main/scala/utility/SRAMTemplate.scala:198:44
  reg         holdRidx_hold_data;	// utility/src/main/scala/utility/Hold.scala:24:82
  wire        holdRidx = holdRidx_REG ? ridx : holdRidx_hold_data;	// utility/src/main/scala/utility/Hold.scala:24:82, :25:8, utility/src/main/scala/utility/SRAMTemplate.scala:189:21, :198:44
  always @(posedge clock) begin
    ridx <= io_r_req_bits_setIdx[0];	// utility/src/main/scala/utility/SRAMTemplate.scala:189:{21,58}
    holdRidx_REG <= io_r_req_valid;	// utility/src/main/scala/utility/SRAMTemplate.scala:198:44
    if (holdRidx_REG)	// utility/src/main/scala/utility/SRAMTemplate.scala:198:44
      holdRidx_hold_data <= ridx;	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:189:21
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// utility/src/main/scala/utility/SRAMTemplate.scala:162:7
    `ifdef FIRRTL_BEFORE_INITIAL	// utility/src/main/scala/utility/SRAMTemplate.scala:162:7
      `FIRRTL_BEFORE_INITIAL	// utility/src/main/scala/utility/SRAMTemplate.scala:162:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// utility/src/main/scala/utility/SRAMTemplate.scala:162:7
    initial begin	// utility/src/main/scala/utility/SRAMTemplate.scala:162:7
      `ifdef INIT_RANDOM_PROLOG_	// utility/src/main/scala/utility/SRAMTemplate.scala:162:7
        `INIT_RANDOM_PROLOG_	// utility/src/main/scala/utility/SRAMTemplate.scala:162:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// utility/src/main/scala/utility/SRAMTemplate.scala:162:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// utility/src/main/scala/utility/SRAMTemplate.scala:162:7
        ridx = _RANDOM[/*Zero width*/ 1'b0][0];	// utility/src/main/scala/utility/SRAMTemplate.scala:162:7, :189:21
        holdRidx_REG = _RANDOM[/*Zero width*/ 1'b0][1];	// utility/src/main/scala/utility/SRAMTemplate.scala:162:7, :189:21, :198:44
        holdRidx_hold_data = _RANDOM[/*Zero width*/ 1'b0][2];	// utility/src/main/scala/utility/Hold.scala:24:82, utility/src/main/scala/utility/SRAMTemplate.scala:162:7, :189:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// utility/src/main/scala/utility/SRAMTemplate.scala:162:7
      `FIRRTL_AFTER_INITIAL	// utility/src/main/scala/utility/SRAMTemplate.scala:162:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  SRAMTemplate_39 array (	// utility/src/main/scala/utility/SRAMTemplate.scala:179:21
    .clock                       (clock),
    .reset                       (reset),
    .io_r_req_valid              (io_r_req_valid),
    .io_r_req_bits_setIdx        (io_r_req_bits_setIdx[7:1]),	// utility/src/main/scala/utility/SRAMTemplate.scala:188:36
    .io_r_resp_data_0_tag        (_array_io_r_resp_data_0_tag),
    .io_r_resp_data_0_ctr        (_array_io_r_resp_data_0_ctr),
    .io_r_resp_data_0_target     (_array_io_r_resp_data_0_target),
    .io_r_resp_data_1_tag        (_array_io_r_resp_data_1_tag),
    .io_r_resp_data_1_ctr        (_array_io_r_resp_data_1_ctr),
    .io_r_resp_data_1_target     (_array_io_r_resp_data_1_target),
    .io_w_req_valid              (io_w_req_valid),
    .io_w_req_bits_setIdx        (io_w_req_bits_setIdx[7:1]),	// utility/src/main/scala/utility/SRAMTemplate.scala:205:36
    .io_w_req_bits_data_0_tag    (io_w_req_bits_data_0_tag),
    .io_w_req_bits_data_0_ctr    (io_w_req_bits_data_0_ctr),
    .io_w_req_bits_data_0_target (io_w_req_bits_data_0_target),
    .io_w_req_bits_data_1_tag    (io_w_req_bits_data_0_tag),
    .io_w_req_bits_data_1_ctr    (io_w_req_bits_data_0_ctr),
    .io_w_req_bits_data_1_target (io_w_req_bits_data_0_target),
    .io_w_req_bits_waymask       (2'h1 << io_w_req_bits_setIdx[0])	// src/main/scala/chisel3/util/OneHot.scala:58:35, :65:12, utility/src/main/scala/utility/SRAMTemplate.scala:206:54
  );
  assign io_r_resp_data_0_tag =
    (holdRidx ? 9'h0 : _array_io_r_resp_data_0_tag)
    | (holdRidx ? _array_io_r_resp_data_1_tag : 9'h0);	// src/main/scala/chisel3/util/Mux.scala:30:73, utility/src/main/scala/utility/Hold.scala:25:8, utility/src/main/scala/utility/SRAMTemplate.scala:162:7, :179:21
  assign io_r_resp_data_0_ctr =
    (holdRidx ? 2'h0 : _array_io_r_resp_data_0_ctr)
    | (holdRidx ? _array_io_r_resp_data_1_ctr : 2'h0);	// src/main/scala/chisel3/util/Mux.scala:30:73, utility/src/main/scala/utility/Hold.scala:25:8, utility/src/main/scala/utility/SRAMTemplate.scala:162:7, :179:21
  assign io_r_resp_data_0_target =
    (holdRidx ? 39'h0 : _array_io_r_resp_data_0_target)
    | (holdRidx ? _array_io_r_resp_data_1_target : 39'h0);	// src/main/scala/chisel3/util/Mux.scala:30:73, utility/src/main/scala/utility/Hold.scala:25:8, utility/src/main/scala/utility/SRAMTemplate.scala:162:7, :179:21
endmodule

