// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// VCS coverage exclude_file
module data_16x16(	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
  input  [3:0]  R0_addr,
  input         R0_en,
  input         R0_clk,
  output [15:0] R0_data,
  input  [3:0]  W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [15:0] W0_data,
  input  [3:0]  W1_addr,
  input         W1_en,
  input         W1_clk,
  input  [15:0] W1_data
);

  reg [15:0] Memory[0:15];	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
  always @(posedge W0_clk) begin	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
    if (W0_en & 1'h1)	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
      Memory[W0_addr] <= W0_data;	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
    if (W1_en & 1'h1)	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
      Memory[W1_addr] <= W1_data;	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
    reg [31:0] _RANDOM_MEM;	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
    initial begin	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
      `INIT_RANDOM_PROLOG_	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
      `ifdef RANDOMIZE_MEM_INIT	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
        for (logic [4:0] i = 5'h0; i < 5'h10; i += 5'h1) begin
          _RANDOM_MEM = `RANDOM;	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
          Memory[i[3:0]] = _RANDOM_MEM[15:0];	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
        end	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 16'bx;	// utility/src/main/scala/utility/DataModuleTemplate.scala:211:17
endmodule

