// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module ITTageTable_3(	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7]
  input         clock,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7]
  input         reset,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7]
  input         io_req_valid,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  input  [40:0] io_req_bits_pc,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  input  [8:0]  io_req_bits_folded_hist_hist_6_folded_hist,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  input  [7:0]  io_req_bits_folded_hist_hist_2_folded_hist,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  output        io_resp_valid,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  output [1:0]  io_resp_bits_ctr,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  output [1:0]  io_resp_bits_u,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  output [40:0] io_resp_bits_target,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  input  [40:0] io_update_pc,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  input  [8:0]  io_update_folded_hist_hist_6_folded_hist,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  input  [7:0]  io_update_folded_hist_hist_2_folded_hist,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  input         io_update_valid,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  input         io_update_correct,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  input         io_update_alloc,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  input  [1:0]  io_update_oldCtr,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  input         io_update_uValid,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  input         io_update_u,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  input         io_update_reset_u,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  input  [40:0] io_update_target,	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
  input  [40:0] io_update_old_target	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
);

  wire        _resp_invalid_by_write_T_2;	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
  wire        _wrbypass_io_hit;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:270:24]
  wire [1:0]  _wrbypass_io_hit_data_0_bits;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:270:24]
  wire        _table_banks_1_io_r_resp_data_0_valid;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:217:44]
  wire [8:0]  _table_banks_1_io_r_resp_data_0_tag;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:217:44]
  wire [1:0]  _table_banks_1_io_r_resp_data_0_ctr;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:217:44]
  wire [40:0] _table_banks_1_io_r_resp_data_0_target;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:217:44]
  wire        _table_banks_0_io_r_resp_data_0_valid;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:217:44]
  wire [8:0]  _table_banks_0_io_r_resp_data_0_tag;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:217:44]
  wire [1:0]  _table_banks_0_io_r_resp_data_0_ctr;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:217:44]
  wire [40:0] _table_banks_0_io_r_resp_data_0_target;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:217:44]
  wire        _us_io_rdata_0;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:215:18]
  wire [8:0]  s0_idx = io_req_bits_pc[9:1] ^ io_req_bits_folded_hist_hist_6_folded_hist;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:181:31, :205:43]
  reg  [8:0]  s1_tag;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:211:68]
  reg         s1_bank_req_1h_0;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:213:33]
  reg         s1_bank_req_1h_1;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:213:33]
  reg         s1_bank_has_write_on_this_req_0;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:239:48]
  reg         s1_bank_has_write_on_this_req_1;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:239:48]
  wire [8:0]  update_idx = io_update_pc[9:1] ^ io_update_folded_hist_hist_6_folded_hist;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:181:31, :205:43]
  wire [8:0]  update_tag =
    io_update_pc[18:10] ^ io_update_folded_hist_hist_6_folded_hist
    ^ {io_update_folded_hist_hist_2_folded_hist, 1'h0};	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7, :182:{32,52,61,75}, :205:43]
  assign _resp_invalid_by_write_T_2 =
    s1_bank_req_1h_0 & s1_bank_has_write_on_this_req_0 | s1_bank_req_1h_1
    & s1_bank_has_write_on_this_req_1;	// @[src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/xiangshan/frontend/ITTAGE.scala:213:33, :239:48]
  wire        _s1_bank_has_write_on_this_req_WIRE_0 = io_update_valid & ~(update_idx[0]);	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:160:{66,86}, :181:{31,40}, :254:33]
  wire        _s1_bank_has_write_on_this_req_WIRE_1 = io_update_valid & update_idx[0];	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:160:66, :181:{31,40}, :254:33]
  wire [1:0]  old_ctr =
    _wrbypass_io_hit ? _wrbypass_io_hit_data_0_bits : io_update_oldCtr;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:270:24, :276:20]
  wire        update_wdata_ctr_oldSatNotTaken = old_ctr == 2'h0;	// @[src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/xiangshan/frontend/BPU.scala:96:30, src/main/scala/xiangshan/frontend/ITTAGE.scala:276:20]
  wire [1:0]  update_wdata_ctr =
    io_update_alloc
      ? 2'h2
      : (&old_ctr) & io_update_correct
          ? 2'h3
          : update_wdata_ctr_oldSatNotTaken & ~io_update_correct
              ? 2'h0
              : io_update_correct ? 2'(old_ctr + 2'h1) : 2'(old_ctr - 2'h1);	// @[src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/xiangshan/frontend/BPU.scala:95:27, :96:30, :97:{8,21}, :98:{10,26,29}, :99:{12,24,35}, src/main/scala/xiangshan/frontend/ITTAGE.scala:276:20, :278:28]
  wire [40:0] update_wdata_target =
    io_update_alloc | update_wdata_ctr_oldSatNotTaken
      ? io_update_target
      : io_update_old_target;	// @[src/main/scala/xiangshan/frontend/BPU.scala:96:30, src/main/scala/xiangshan/frontend/ITTAGE.scala:281:{29,46}]
  always @(posedge clock) begin	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7]
    if (io_req_valid) begin	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:145:14]
      s1_tag <=
        io_req_bits_pc[18:10] ^ io_req_bits_folded_hist_hist_6_folded_hist
        ^ {io_req_bits_folded_hist_hist_2_folded_hist, 1'h0};	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7, :182:{32,52,61,75}, :205:43, :211:68]
      s1_bank_req_1h_0 <= ~(s0_idx[0]);	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:160:{66,86}, :181:{31,40}, :213:33]
      s1_bank_req_1h_1 <= s0_idx[0];	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:160:66, :181:{31,40}, :213:33]
      s1_bank_has_write_on_this_req_0 <= _s1_bank_has_write_on_this_req_WIRE_0;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:239:48, :254:33]
      s1_bank_has_write_on_this_req_1 <= _s1_bank_has_write_on_this_req_WIRE_1;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:239:48, :254:33]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7]
    initial begin	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7]
        s1_tag = _RANDOM[/*Zero width*/ 1'b0][17:9];	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7, :211:68]
        s1_bank_req_1h_0 = _RANDOM[/*Zero width*/ 1'b0][18];	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7, :211:68, :213:33]
        s1_bank_req_1h_1 = _RANDOM[/*Zero width*/ 1'b0][19];	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7, :211:68, :213:33]
        s1_bank_has_write_on_this_req_0 = _RANDOM[/*Zero width*/ 1'b0][20];	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7, :211:68, :239:48]
        s1_bank_has_write_on_this_req_1 = _RANDOM[/*Zero width*/ 1'b0][21];	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7, :211:68, :239:48]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Folded1WDataModuleTemplate_2 us (	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:215:18]
    .clock      (clock),
    .reset      (reset),
    .io_ren_0   (io_req_valid),
    .io_raddr_0 (s0_idx),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:181:31]
    .io_rdata_0 (_us_io_rdata_0),
    .io_wen     (io_update_uValid),
    .io_waddr   (update_idx),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:181:31]
    .io_wdata   (io_update_u),
    .io_resetEn (io_update_reset_u)
  );
  FoldedSRAMTemplate_25 table_banks_0 (	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:217:44]
    .clock                       (clock),
    .reset                       (reset),
    .io_r_req_valid              (io_req_valid & ~(s0_idx[0])),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:160:{66,86}, :181:{31,40}, :221:50]
    .io_r_req_bits_setIdx        (s0_idx[8:1]),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:161:37, :181:{31,40}]
    .io_r_resp_data_0_valid      (_table_banks_0_io_r_resp_data_0_valid),
    .io_r_resp_data_0_tag        (_table_banks_0_io_r_resp_data_0_tag),
    .io_r_resp_data_0_ctr        (_table_banks_0_io_r_resp_data_0_ctr),
    .io_r_resp_data_0_target     (_table_banks_0_io_r_resp_data_0_target),
    .io_w_req_valid              (_s1_bank_has_write_on_this_req_WIRE_0),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:254:33]
    .io_w_req_bits_setIdx        (update_idx[8:1]),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:161:37, :181:{31,40}]
    .io_w_req_bits_data_0_tag    (update_tag),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:182:61]
    .io_w_req_bits_data_0_ctr    (update_wdata_ctr),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:278:28]
    .io_w_req_bits_data_0_target (update_wdata_target)	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:281:29]
  );
  FoldedSRAMTemplate_25 table_banks_1 (	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:217:44]
    .clock                       (clock),
    .reset                       (reset),
    .io_r_req_valid              (io_req_valid & s0_idx[0]),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:160:66, :181:{31,40}, :221:50]
    .io_r_req_bits_setIdx        (s0_idx[8:1]),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:161:37, :181:{31,40}]
    .io_r_resp_data_0_valid      (_table_banks_1_io_r_resp_data_0_valid),
    .io_r_resp_data_0_tag        (_table_banks_1_io_r_resp_data_0_tag),
    .io_r_resp_data_0_ctr        (_table_banks_1_io_r_resp_data_0_ctr),
    .io_r_resp_data_0_target     (_table_banks_1_io_r_resp_data_0_target),
    .io_w_req_valid              (_s1_bank_has_write_on_this_req_WIRE_1),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:254:33]
    .io_w_req_bits_setIdx        (update_idx[8:1]),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:161:37, :181:{31,40}]
    .io_w_req_bits_data_0_tag    (update_tag),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:182:61]
    .io_w_req_bits_data_0_ctr    (update_wdata_ctr),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:278:28]
    .io_w_req_bits_data_0_target (update_wdata_target)	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:281:29]
  );
  WrBypass_43 wrbypass (	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:270:24]
    .clock              (clock),
    .reset              (reset),
    .io_wen             (io_update_valid),
    .io_write_idx       (update_idx),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:181:31]
    .io_write_data_0    (update_wdata_ctr),	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:278:28]
    .io_hit             (_wrbypass_io_hit),
    .io_hit_data_0_bits (_wrbypass_io_hit_data_0_bits)
  );
  assign io_resp_valid =
    (s1_bank_req_1h_0 & _table_banks_0_io_r_resp_data_0_valid | s1_bank_req_1h_1
     & _table_banks_1_io_r_resp_data_0_valid)
    & ((s1_bank_req_1h_0 ? _table_banks_0_io_r_resp_data_0_tag : 9'h0)
       | (s1_bank_req_1h_1 ? _table_banks_1_io_r_resp_data_0_tag : 9'h0)) == s1_tag
    & ~_resp_invalid_by_write_T_2;	// @[src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7, :211:68, :213:33, :217:44, :231:62, :234:{50,53}]
  assign io_resp_bits_ctr =
    (s1_bank_req_1h_0 ? _table_banks_0_io_r_resp_data_0_ctr : 2'h0)
    | (s1_bank_req_1h_1 ? _table_banks_1_io_r_resp_data_0_ctr : 2'h0);	// @[src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7, :213:33, :217:44]
  assign io_resp_bits_u = {1'h0, _us_io_rdata_0};	// @[src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7, :215:18, :236:18]
  assign io_resp_bits_target =
    (s1_bank_req_1h_0 ? _table_banks_0_io_r_resp_data_0_target : 41'h0)
    | (s1_bank_req_1h_1 ? _table_banks_1_io_r_resp_data_0_target : 41'h0);	// @[src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/xiangshan/frontend/ITTAGE.scala:140:7, :213:33, :217:44]
endmodule

